---
development:
  dialect: postgres
  database: api
  user: api
  password: api
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://api:api@127.0.0.1:5432/api_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/account_production?sslmode=disable"}}
