CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS USERS(
  id SERIAL NOT NULL UNIQUE PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  secret uuid not null unique DEFAULT uuid_generate_v4(),
  password VARCHAR(60) NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

